# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Vivado/Projects/lab5/lab5.cache/wt [current_project]
set_property parent.project_path E:/Vivado/Projects/lab5/lab5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Vivado/Projects/lab5/lab5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  E:/Vivado/Projects/lab5/lab5.srcs/sources_1/imports/lol/accelerometer.sv
  E:/Vivado/Projects/lab5/lab5.srcs/sources_1/new/keyboard.sv
  E:/Vivado/Projects/lab5/lab5.srcs/sources_1/new/montek_sound_Nexys4.sv
  E:/Vivado/Projects/lab5/lab5.srcs/sources_1/new/io_demo.sv
}
read_vhdl -library xil_defaultlib {
  E:/Vivado/Projects/lab5/lab5.srcs/sources_1/imports/lol/ADXL362Ctrl.vhd
  E:/Vivado/Projects/lab5/lab5.srcs/sources_1/imports/lol/AccelArithmetics.vhd
  E:/Vivado/Projects/lab5/lab5.srcs/sources_1/imports/lol/AccelerometerCtl.vhd
  E:/Vivado/Projects/lab5/lab5.srcs/sources_1/imports/lol/SPI_If.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Vivado/Projects/lab5/lab5.srcs/constrs_1/imports/new/segdisplay.xdc
set_property used_in_implementation false [get_files E:/Vivado/Projects/lab5/lab5.srcs/constrs_1/imports/new/segdisplay.xdc]

read_xdc E:/Vivado/Projects/lab5/lab5.srcs/constrs_1/new/clock.xdc
set_property used_in_implementation false [get_files E:/Vivado/Projects/lab5/lab5.srcs/constrs_1/new/clock.xdc]

read_xdc E:/Vivado/Projects/lab5/lab5.srcs/constrs_1/new/keyboard.xdc
set_property used_in_implementation false [get_files E:/Vivado/Projects/lab5/lab5.srcs/constrs_1/new/keyboard.xdc]

read_xdc E:/Vivado/Projects/lab5/lab5.srcs/constrs_1/new/sound.xdc
set_property used_in_implementation false [get_files E:/Vivado/Projects/lab5/lab5.srcs/constrs_1/new/sound.xdc]

read_xdc E:/Vivado/Projects/lab5/lab5.srcs/constrs_1/new/accel.xdc
set_property used_in_implementation false [get_files E:/Vivado/Projects/lab5/lab5.srcs/constrs_1/new/accel.xdc]

read_xdc E:/Vivado/Projects/lab5/lab5.srcs/constrs_1/new/led.xdc
set_property used_in_implementation false [get_files E:/Vivado/Projects/lab5/lab5.srcs/constrs_1/new/led.xdc]


synth_design -top io_demo -part xc7a100tcsg324-1


write_checkpoint -force -noxdef io_demo.dcp

catch { report_utilization -file io_demo_utilization_synth.rpt -pb io_demo_utilization_synth.pb }
