# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Vivado/Projects/lab6/lab6.cache/wt [current_project]
set_property parent.project_path E:/Vivado/Projects/lab6/lab6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Vivado/Projects/lab6/lab6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  E:/Vivado/Projects/lab6/lab6.srcs/sources_1/new/debouncer.sv
  E:/Vivado/Projects/lab6/lab6.srcs/sources_1/imports/new/display8digit.sv
  E:/Vivado/Projects/lab6/lab6.srcs/sources_1/new/fsm.sv
  E:/Vivado/Projects/lab6/lab6.srcs/sources_1/imports/new/hexto7seg.sv
  E:/Vivado/Projects/lab6/lab6.srcs/sources_1/new/updowncounter.sv
  E:/Vivado/Projects/lab6/lab6.srcs/sources_1/new/stopwatch.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Vivado/Projects/lab6/lab6.srcs/constrs_1/imports/constrs_1/imports/new/segdisplay.xdc
set_property used_in_implementation false [get_files E:/Vivado/Projects/lab6/lab6.srcs/constrs_1/imports/constrs_1/imports/new/segdisplay.xdc]

read_xdc E:/Vivado/Projects/lab6/lab6.srcs/constrs_1/imports/constrs_1/new/clock.xdc
set_property used_in_implementation false [get_files E:/Vivado/Projects/lab6/lab6.srcs/constrs_1/imports/constrs_1/new/clock.xdc]

read_xdc E:/Vivado/Projects/lab6/lab6.srcs/constrs_1/new/buttons.xdc
set_property used_in_implementation false [get_files E:/Vivado/Projects/lab6/lab6.srcs/constrs_1/new/buttons.xdc]


synth_design -top stopwatch -part xc7a100tcsg324-1


write_checkpoint -force -noxdef stopwatch.dcp

catch { report_utilization -file stopwatch_utilization_synth.rpt -pb stopwatch_utilization_synth.pb }
