# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Vivado/Projects/lab8/lab8.cache/wt [current_project]
set_property parent.project_path E:/Vivado/Projects/lab8/lab8.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Vivado/Projects/lab8/lab8.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  E:/Vivado/Projects/lab8/lab8.srcs/sources_1/imports/sources_1/imports/sources_1/new/ALU.sv
  E:/Vivado/Projects/lab8/lab8.srcs/sources_1/imports/sources_1/imports/sources_1/new/adder.sv
  E:/Vivado/Projects/lab8/lab8.srcs/sources_1/imports/sources_1/imports/sources_1/new/addsub.sv
  E:/Vivado/Projects/lab8/lab8.srcs/sources_1/imports/sources_1/imports/sources_1/new/comparator.sv
  E:/Vivado/Projects/lab8/lab8.srcs/sources_1/new/controller.sv
  E:/Vivado/Projects/lab8/lab8.srcs/sources_1/imports/sources_1/new/datapath.sv
  E:/Vivado/Projects/lab8/lab8.srcs/sources_1/new/dmem.sv
  E:/Vivado/Projects/lab8/lab8.srcs/sources_1/imports/new/fulladder.sv
  E:/Vivado/Projects/lab8/lab8.srcs/sources_1/new/imem.sv
  E:/Vivado/Projects/lab8/lab8.srcs/sources_1/imports/sources_1/imports/sources_1/new/logical.sv
  E:/Vivado/Projects/lab8/lab8.srcs/sources_1/new/mips.sv
  E:/Vivado/Projects/lab8/lab8.srcs/sources_1/new/programcounter.sv
  E:/Vivado/Projects/lab8/lab8.srcs/sources_1/imports/sources_1/new/register_file.sv
  E:/Vivado/Projects/lab8/lab8.srcs/sources_1/imports/sources_1/imports/sources_1/new/shifter.sv
  E:/Vivado/Projects/lab8/lab8.srcs/sources_1/new/top.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Vivado/Projects/lab8/lab8.srcs/constrs_1/imports/new/clock.xdc
set_property used_in_implementation false [get_files E:/Vivado/Projects/lab8/lab8.srcs/constrs_1/imports/new/clock.xdc]

read_xdc E:/Vivado/Projects/lab8/lab8.srcs/constrs_1/new/reset.xdc
set_property used_in_implementation false [get_files E:/Vivado/Projects/lab8/lab8.srcs/constrs_1/new/reset.xdc]


synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
