# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Vivado/Projects/lab4/lab4.cache/wt [current_project]
set_property parent.project_path E:/Vivado/Projects/lab4/lab4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Vivado/Projects/lab4/lab4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog E:/Vivado/Projects/lab4/lab4.srcs/sources_1/new/display640x480.vh
read_verilog -library xil_defaultlib -sv {
  E:/Vivado/Projects/lab4/lab4.srcs/sources_1/new/vgatimer.sv
  E:/Vivado/Projects/lab4/lab4.srcs/sources_1/imports/new/xycounter.sv
  E:/Vivado/Projects/lab4/lab4.srcs/sources_1/new/vgadisplaydriver.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Vivado/Projects/lab4/lab4.srcs/constrs_1/new/clock.xdc
set_property used_in_implementation false [get_files E:/Vivado/Projects/lab4/lab4.srcs/constrs_1/new/clock.xdc]

read_xdc E:/Vivado/Projects/lab4/lab4.srcs/constrs_1/new/vga.xdc
set_property used_in_implementation false [get_files E:/Vivado/Projects/lab4/lab4.srcs/constrs_1/new/vga.xdc]


synth_design -top vgadisplaydriver -part xc7a100tcsg324-1


write_checkpoint -force -noxdef vgadisplaydriver.dcp

catch { report_utilization -file vgadisplaydriver_utilization_synth.rpt -pb vgadisplaydriver_utilization_synth.pb }
